### ISSUE TITLE
Plural macro does not support description prop

### ISSUE THREAD

**Issue by kenpowers-signal** [lingui/js-lingui#532]
**Describe the bug**

When using the `Plural` macro with React (and TypeScript), specifying a `description` prop causes `extract` to fail with the following error:

> SyntaxError: @lingui/macro: .../search.tsx: Invalid plural rule 'description'. Must be zero, one, two, few, many, other or extract number depending on your source language ('one' and 'other' for English).

**To Reproduce**

```
import { Plural } from "@lingui/macro"

export default function App() {
   return <Plural description="test comment" value={10} one="# blah" other="# blahs" />
}
```

**Expected behavior**

The TypeScript typings allow for a `description` prop on `Plural`, I would expect that it would work the same as the `description` prop on `Trans`.

**Additional context**

I tried modifying the code to bypass validation for the `description` prop; however, the description doesn't get extracted, instead it becomes a plural rule in the extracted `po` file:

```po
#: src/app/search/search.tsx:70
msgid "{0, plural, description {test comment} one {# blah} other {# blahs}}"
msgstr ""
```

I've also tried wrapping the `Plural` in a `Trans` from `lingui/macro` but that results in the message not getting extracted at all.

**Comment by tricoder42** [comment]
Hey @kenpowers-signal, what version is it? The `latest` or `next`?

**Comment by kenpowers-signal** [comment]
I just upgraded `@lingui/{macro,react,cli}` to `2.8.3` and encountered this issue.

![image](https://user-images.githubusercontent.com/49649953/60458505-c7f87400-9c0c-11e9-9024-80281de1f30f.png)

![image](https://user-images.githubusercontent.com/49649953/60458628-1d348580-9c0d-11e9-816d-95d0c27d6e29.png)

**Comment by tricoder42** [comment]
I see. Sorry for the problems.

If you would like to fix this issue in `master`, you probably just need to add `description` to this line: https://github.com/lingui/js-lingui/blob/master/packages/babel-plugin-transform-react/src/transformer.js#L2

I believe this issue is already fixed in `next`. I'll check and fix it myself if it isn't. I want to focus on `next` so I can release it asap.

**Comment by kenpowers-signal** [comment]
@tricoder42 that change doesn't appear to fix the issue. I'm still getting the same problem.

**Comment by tricoder42** [comment]
> EDIT 2: I just tried linking to a local build with that change, still the same issue.

In `next` version, the `description` prop has been renamed to `comment`. I'll check if it's supported though.

**Comment by tricoder42** [comment]
@kenpowers-signal v3 has just been released few days ago. Could you please check if this is still hapenning? Feel free to reopen if so.
